### ISSUE TITLE
申请新加生僻字：女当和土夭

### ISSUE THREAD

**Issue by cxywf9337** [alipay/Z-RareCharacterSolution#16]
浙江丽水部分地区的实有人口姓名含有这2个生僻字，在Z字库中未查询到，感谢大佬的支持。 
𫰠 扩E：2BC20 同【[㜭](http://www.yedict.com/zsCONTENT.ASP?uni=372D)】字。
𱖎 扩H：3158E 同【[坳](http://www.yedict.com/zsCONTENT.ASP?uni=5773)或[懊](http://www.yedict.com/zsCONTENT.ASP?uni=61CA)】字。

**Comment by Andyliwr** [comment]
增补字体的MR：[!7:feat: 新增自行添补汉字的工具和文档](https://gitee.com/ant-zsolution/Z-RareCharacterSolution/pulls/7)
后续有新的字可以参考这个文档自己新增 [Z字库新增汉字指南](https://github.com/alipay/Z-RareCharacterSolution/blob/main/docs/Add_chars_into_ZDatas.md)，也可以提交MR给我们合并到官网字库里
