### ISSUE TITLE
Letter of Commendation

### ISSUE THREAD

**Issue by WittyWen** [alipay/Z-RareCharacterSolution#5]
This solution supports the mandatory national standard GB18030, providing great convenience for developers and receiving unanimous recognition from the people with rare characters in their names. Ant Group has practiced the spirit of openness, sharing, and cooperation with practical actions, making positive contributions to the development of Chinese information processing technology and benefiting the present and the future.

**Comment by shaohuapsh** [comment]
Thank you, my friend.
