### ISSUE TITLE
能否支持 ‘分石’、‘鸟甲’ 这两个字

### ISSUE THREAD

**Issue by guziwen-lab** [alipay/Z-RareCharacterSolution#9]
# 能否支持 ‘分石’ 这个字

我们项目里需要显示和输入这两个字 ‘分石（la4）’、‘鸟甲( nia4)’，程序能否支持一下

```
unicode：2E00E
可复制字：𮀎
总笔画数：9
部首余笔：石 4
两分字元：分 石
```

```
非unicode临时码：1I2582
可复制字：暂无
总笔画数：9
部首余笔：田 4
两分字元：鸟 甲
```

**Comment by guziwen-lab** [comment]
{
      charId: '531db3',
      unicodeChar: '𮀎',
      unicodeFont: '',
      unicodeCodePoint: '2E00E',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'LA4' }],
      splitChars: [{ char: '分石' }],
      weight: 8,
      extInfo: '',
    },
    {
      charId: '531db4',
      unicodeChar: '𛆿',
      unicodeFont: '',
      unicodeCodePoint: '1B18F',
      puaChar: '',
      puaFont: '',
      puaCodePoint: '',
      pinYinChars: [{ char: 'nia4' }],
      splitChars: [{ char: '鸟甲' }],
      weight: 8,
      extInfo: '',
    },

我的输入配置是这样的

**Comment by Andyliwr** [comment]
![image](https://github.com/alipay/Z-RareCharacterSolution/assets/12456160/c1b35060-7cc5-4096-8add-9c976bb204e7)
![image](https://github.com/alipay/Z-RareCharacterSolution/assets/12456160/e71f2584-7bab-4ac4-91a1-11b8319f995f)
已经支持，但是（鸟甲NIA）是PUA字，暂无正式编码，请慎用
